version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./www:/app
        depends_on:
            - php-fpm
        networks:
              dropbox-gallery-project:
                ipv4_address: 10.8.0.105
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./www:/app
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=mysql"
          - PHP_IDE_CONFIG=serverName=dropbox-gallery
          - XDEBUG_CONFIG=remote_host=10.8.0.105
        depends_on:
            - mysql
        networks:
            dropbox-gallery-project:

    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./www:/app
        depends_on:
            - mysql

        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        tty: true

        networks:
            dropbox-gallery-project:

    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_DATABASE=dropbox-gallery"

        networks:
            dropbox-gallery-project:
              ipv4_address: 10.8.0.106

    nodejs:
        build:
          context: ./
          dockerfile: docker/nodejs.docker
        volumes:
          - ./www:/app
        tty: true
        networks:
          dropbox-gallery-project:
            ipv4_address: 10.8.0.107
networks:
  dropbox-gallery-project:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.8.0.0/24